// This file is auto-generated by generate_api_docs.js. Do not edit manually.

export interface ApiDocItem {
  id: string;
  title: string;
  filename: string;
  content: string;
}

export const authDocContent = `# Auth API — Integration Docs

> **Base URL:** \`https://kbapi.pulsemarketspt.com\`
> **Content-Type:** \`application/json\` cho tất cả request
> **Version:** V1.1 — 2026-05-19 (thêm Refresh Token; bỏ cookie — body-only cho tất cả platform)

---

## Mục lục

- [Response Envelope](#response-envelope)
- [1. Register](#1-register)
- [2. Verify Email](#2-verify-email)
- [3. Resend Verification](#3-resend-verification)
- [4. Login](#4-login)
- [5. Logout](#5-logout)
- [6. Refresh Token](#6-refresh-token)
- [Error Code Catalog](#error-code-catalog)
- [Rate Limits](#rate-limits)
- [Full Flow Sequence](#full-flow-sequence)

---

## Response Envelope

Mọi response đều wrap trong envelope sau:

\`\`\`json
// Success
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": { ... }
}

// Error
{
  "status": "0",
  "error_code": "ERROR_CODE",
  "msg": "Human-readable message",
  "data": { ... }
}
\`\`\`

---

## 1. Register

**\`POST /api/v1/auth/register\`**

Tạo tài khoản mới. Server gửi email verification (hoặc trả \`verificationLink\` nếu bật \`DEBUG_RETURN_VERIFICATION_LINK\`).

> Silent policy: nếu email đã tồn tại, server vẫn trả \`200\` và gửi email thông báo — không leak thông tin email tồn tại.

### Request Body

| Field | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`firstName\` | string | ✅ | 1–80 ký tự |
| \`lastName\` | string | ✅ | 1–80 ký tự |
| \`email\` | string (email) | ✅ | Tự động lowercase |
| \`password\` | string | ✅ | Tối thiểu 8 ký tự, 1 chữ hoa, 1 số |
| \`selectedPlanIntent\` | \`"free"\` \\| \`"pro"\` | ❌ | Default: \`"free"\` |
| \`acceptedTerms\` | boolean | ✅ | Phải là \`true\` |

\`\`\`json
{
  "firstName": "Ben",
  "lastName": "Test",
  "email": "ben@test.com",
  "password": "Secret123!",
  "selectedPlanIntent": "free",
  "acceptedTerms": true
}
\`\`\`

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "userId": "d45bc874-c99f-4538-9708-c5fb83c91ad8",
    "email": "ben@test.com",
    "emailVerified": false,
    "plan": "free",
    "selectedPlanIntent": "free",
    "verificationRequired": true,
    "resendAvailableInSeconds": 60,
    "nextRoute": "/verify-email-pending",
    "verificationLink": "https://.../api/v1/auth/verify-email?token=xxx"
  }
}
\`\`\`

> \`verificationLink\` chỉ có trong môi trường dev (\`DEBUG_RETURN_VERIFICATION_LINK=true\`). Production không có field này.

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 400 | \`VALIDATION_ERROR\` | Request body sai format, thiếu field, password yếu |
| 429 | \`RATE_LIMITED\` | Quá 5 lần trong 15 phút từ cùng email |

---

## 2. Verify Email

**\`GET /api/v1/auth/verify-email?token=<TOKEN>\`**

Xác minh email bằng token nhận được qua email (hoặc \`verificationLink\` từ register response).

### Query Params

| Param | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`token\` | string | ✅ | Raw token từ email/verificationLink |

\`\`\`bash
GET /api/v1/auth/verify-email?token=sisl0fnnEy39eUk2lENhEwoJCNSTC-nDVFALpJvnKA4
\`\`\`

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "emailVerified": true,
    "nextRoute": "/login"
  }
}
\`\`\`

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 400 | \`TOKEN_MISSING\` | Không có \`?token=\` trong URL |
| 400 | \`TOKEN_INVALID\` | Token không tồn tại, đã dùng, hoặc hash không khớp |
| 400 | \`TOKEN_EXPIRED\` | Token tồn tại nhưng đã hết hạn (> 24h) |
| 409 | \`EMAIL_ALREADY_VERIFIED\` | Email đã được verify trước đó |
| 429 | \`RATE_LIMITED\` | Quá 10 lần trong 15 phút từ cùng IP |

---

## 3. Resend Verification

**\`POST /api/v1/auth/resend-verification\`**

Gửi lại email verification. Silent — không tiết lộ email có tồn tại hay không.

### Request Body

| Field | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`email\` | string (email) | ✅ | Email cần gửi lại |

\`\`\`json
{
  "email": "ben@test.com"
}
\`\`\`

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "sentIfEligible": true,
    "resendAvailableInSeconds": 60
  }
}
\`\`\`

> \`sentIfEligible: true\` không đồng nghĩa email thật sự được gửi — server luôn trả \`true\` để tránh enumeration.
> \`resendAvailableInSeconds\`: cooldown còn lại trước khi có thể resend lần nữa.

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 429 | \`RATE_LIMITED\` | Quá 3 lần trong 15 phút từ cùng email |

---

## 4. Login

**\`POST /api/v1/auth/login\`**

Đăng nhập. Trả \`accessToken\` (JWT, TTL 15 phút) và \`refreshToken\`.

> Header \`X-Platform\` bắt buộc. Với \`web\`: \`refreshToken\` set qua \`HttpOnly\` cookie, không có trong body. Với các platform khác: \`refreshToken\` trả trong body.

### Headers

| Header | Required | Giá trị hợp lệ |
|--------|----------|---------------|
| \`X-Platform\` | ✅ | \`web\` \\| \`mobile_ios\` \\| \`mobile_android\` \\| \`desktop\` |

### Request Body

| Field | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`email\` | string (email) | ✅ | |
| \`password\` | string | ✅ | Tối đa 1024 ký tự |
| \`returnUrl\` | string | ❌ | URL redirect sau login, tối đa 2048 ký tự |

\`\`\`json
{
  "email": "ben@test.com",
  "password": "Secret123!"
}
\`\`\`

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "user": {
      "id": "d45bc874-c99f-4538-9708-c5fb83c91ad8",
      "email": "ben@test.com",
      "firstName": "Ben",
      "lastName": "Test",
      "displayName": "Ben Test",
      "emailVerified": true,
      "plan": "free",
      "selectedPlanIntent": "free",
      "onboardingStatus": "pending"
    },
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
    "tokenType": "Bearer",
    "expiresIn": 900,
    "nextRoute": "/onboarding",
    "refreshToken": "4lofM4OZZNbCuZCVHO6NiXjLHVhplu0R-0bBXYpMH-A"
  }
}
\`\`\`

> \`refreshToken\` có trong body cho tất cả platform. *(V1.1: bỏ HttpOnly cookie — body-only)*

### \`nextRoute\` logic

| \`onboardingStatus\` | \`nextRoute\` |
|--------------------|-------------|
| \`pending\` | \`/onboarding\` |
| \`completed\` | \`/dashboard\` |

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 400 | \`VALIDATION_ERROR\` | \`X-Platform\` không hợp lệ |
| 401 | \`INVALID_CREDENTIALS\` | Email không tồn tại hoặc sai password |
| 403 | \`EMAIL_NOT_VERIFIED\` | Tài khoản chưa verify email |
| 423 | \`ACCOUNT_LOCKED\` | Tài khoản bị lock tạm thời (quá nhiều lần sai) |
| 429 | \`RATE_LIMITED\` | Quá 5 lần trong 15 phút từ cùng email, \`data.retryAfterSeconds\` chứa cooldown |

---

## 5. Logout

**\`POST /api/v1/auth/logout\`**

Invalidate access token (JTI blacklist). Tùy chọn revoke refresh token hoặc logout tất cả thiết bị.

> Yêu cầu \`Authorization: Bearer <accessToken>\`.

### Headers

| Header | Required | Mô tả |
|--------|----------|-------|
| \`Authorization\` | ✅ | \`Bearer <accessToken>\` |

### Request Body (optional)

| Field | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`refreshToken\` | string | ❌ | Nếu truyền, revoke refresh token này |
| \`allDevices\` | boolean | ❌ | \`true\` = logout tất cả thiết bị. Default: \`false\` |

\`\`\`json
{}
\`\`\`

\`\`\`json
{
  "refreshToken": "4lofM4OZZNbCuZCVHO6NiXjLHVhplu0R-0bBXYpMH-A",
  "allDevices": false
}
\`\`\`

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {}
}
\`\`\`

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 401 | \`UNAUTHORIZED\` | Token không hợp lệ, hết hạn, hoặc đã bị blacklist |

---

## 6. Refresh Token

**\`POST /api/v1/auth/refresh\`**

Đổi refresh token lấy access token mới (token rotation). Phát hiện reuse → revoke cả family.

> Không yêu cầu \`Authorization\` header. Token truyền qua body.

### Request Body

| Field | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`refreshToken\` | string | ✅ | Raw refresh token nhận từ login hoặc refresh trước đó |

\`\`\`json
{
  "refreshToken": "4lofM4OZZNbCuZCVHO6NiXjLHVhplu0R-0bBXYpMH-A"
}
\`\`\`

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
    "refreshToken": "9mKpN3RYZxBtCuDVHO7OjYmMIWhqmv1S-1cCZRqNL-B",
    "tokenType": "Bearer",
    "expiresIn": 900
  }
}
\`\`\`

> Token cũ bị invalidate sau khi rotate. FE phải lưu token mới vào secure storage ngay lập tức.

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 401 | \`MISSING_REFRESH_TOKEN\` | Không có \`refreshToken\` trong body |
| 401 | \`INVALID_REFRESH_TOKEN\` | Token không tồn tại, đã bị revoke, user bị suspend/delete, hoặc race condition |
| 401 | \`REFRESH_TOKEN_EXPIRED\` | Token hết hạn — FE redirect về \`/login\` |
| 401 | \`REFRESH_TOKEN_REUSED\` | Token đã dùng bị submit lại → toàn bộ family bị revoke, bắt buộc re-login |

---

## Error Code Catalog

| \`error_code\` | HTTP | Mô tả |
|-------------|------|-------|
| \`VALIDATION_ERROR\` | 400 | Request body sai format hoặc thiếu field bắt buộc |
| \`TOKEN_MISSING\` | 400 | Thiếu \`?token=\` trong URL |
| \`TOKEN_INVALID\` | 400 | Token không hợp lệ hoặc đã dùng |
| \`TOKEN_EXPIRED\` | 400 | Token hết hạn |
| \`UNAUTHORIZED\` | 401 | Access token không hợp lệ hoặc hết hạn |
| \`INVALID_CREDENTIALS\` | 401 | Sai email hoặc password |
| \`EMAIL_NOT_VERIFIED\` | 403 | Email chưa được verify |
| \`EMAIL_ALREADY_VERIFIED\` | 409 | Email đã được verify trước đó |
| \`ACCOUNT_LOCKED\` | 423 | Tài khoản bị lock tạm thời |
| \`RATE_LIMITED\` | 429 | Quá số lần cho phép, xem \`data.retryAfterSeconds\` |
| \`MISSING_REFRESH_TOKEN\` | 401 | Không có \`refreshToken\` trong body |
| \`INVALID_REFRESH_TOKEN\` | 401 | Refresh token không hợp lệ, đã revoke, hoặc user không còn active |
| \`REFRESH_TOKEN_EXPIRED\` | 401 | Refresh token hết hạn — cần re-login |
| \`REFRESH_TOKEN_REUSED\` | 401 | Token theft detected — toàn bộ family bị revoke, bắt buộc re-login |

---

## Rate Limits

| Endpoint | Limit | Window |
|----------|-------|--------|
| \`POST /register\` | 5 lần / email | 15 phút |
| \`POST /register\` (IP) | 20 lần / IP | 15 phút |
| \`GET /verify-email\` (IP) | 10 lần / IP | 15 phút |
| \`POST /resend-verification\` | 3 lần / email | 15 phút |
| \`POST /login\` (IP) | 20 lần / IP | 15 phút |
| \`POST /login\` | 5 lần / email | 15 phút |
| \`POST /refresh\` | *(chưa có — follow-up)* | — |

---

## Full Flow Sequence

### Register → Verify → Login → Refresh → Logout

\`\`\`
Client                          Server                        DB / Redis
  |                               |                               |
  |-- POST /register ------------>|                               |
  |                               |-- INSERT user --------------->|
  |                               |-- INSERT auth_token --------->|
  |                               |-- send verification email     |
  |<-- 200 { verificationLink } --|                               |
  |                               |                               |
  |-- GET /verify-email?token=xx->|                               |
  |                               |-- GET auth_token by hash ---->|
  |                               |-- UPDATE user.email_verified->|
  |                               |-- UPDATE token.used_at ------>|
  |<-- 200 { nextRoute:/login } --|                               |
  |                               |                               |
  |-- POST /login ---------------->|                               |
  |                               |-- GET user by email --------->|
  |                               |-- verify password             |
  |                               |-- INSERT refresh_token ------>|
  |<-- 200 { accessToken, ... } --|                               |
  |                               |                               |
  |-- POST /logout --------------->|                               |
  |   Authorization: Bearer <at>  |-- decode JWT                  |
  |                               |-- SET jti blacklist --------->|
  |                               |-- revoke refresh_token ------>|
  |<-- 200 {} --------------------|                               |
\`\`\`

### Access Token Expired → Refresh

\`\`\`
Client                          Server                        DB / Redis
  |                               |                               |
  |-- POST /refresh -------------->|                               |
  |   { refreshToken: "<rt>" }    |-- SHA256(raw) → hash          |
  |                               |-- SELECT refresh_tokens ------>|
  |                               |-- check is_used (reuse?)       |
  |                               |-- check revoked_at             |
  |                               |-- check expires_at             |
  |                               |-- SELECT user (active?) ------>|
  |                               |-- [Transaction]                |
  |                               |   UPDATE is_used=TRUE -------->|
  |                               |   INSERT new token ----------->|
  |                               |-- create new JWT               |
  |<-- 200 { accessToken,         |                               |
  |          refreshToken } -------|                               |
\`\`\`

### Refresh Token Reuse (theft detection)

\`\`\`
Client                          Server                        DB
  |                               |                               |
  |-- POST /refresh (old token) -->|                               |
  |                               |-- SELECT: is_used = TRUE      |
  |                               |-- REUSE DETECTED              |
  |                               |-- UPDATE revoked_at all       |
  |                               |    WHERE family_id = <fid> -->|
  |<-- 401 REFRESH_TOKEN_REUSED --|                               |
\`\`\`

### Rate Limited Register (silent policy)

\`\`\`
Client                          Server
  |                               |
  |-- POST /register (email X) -->|
  |   (email already exists)      |-- send "account exists" email
  |<-- 200 (same as new user) ----|   (no error exposed to client)
\`\`\`

### Expired / Invalid Token on Logout

\`\`\`
Client                          Server                        Redis
  |                               |                               |
  |-- POST /logout --------------->|                               |
  |   Authorization: Bearer <at>  |-- decode JWT → expired        |
  |<-- 401 { UNAUTHORIZED } ------|                               |
\`\`\`
`;

export const documentsDocContent = `# Documents & Research API — Integration Docs

> **Base URL:** \`https://kbapi.pulsemarketspt.com\`
> **Content-Type:** \`application/json\` cho tất cả request
> **Version:** V1.0 — 2026-05-30 (auth gate + subfolder migration hoàn thành)

---

## Mục lục

- [Response Envelope](#response-envelope)
- [Authentication](#authentication)
- [1. Submit Document](#1-submit-document)
- [2. Research Stream](#2-research-stream)
- [SSE Event Reference](#sse-event-reference)
- [Error Code Catalog](#error-code-catalog)
- [Full Flow Sequence](#full-flow-sequence)

---

## Response Envelope

Mọi response HTTP đều wrap trong envelope sau (trừ SSE stream — xem [SSE Event Reference](#sse-event-reference)):

\`\`\`json
// Success
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": { ... }
}

// Error
{
  "status": "0",
  "error_code": "ERROR_CODE",
  "msg": "Human-readable message",
  "data": null
}
\`\`\`

---

## Authentication

Cả 2 endpoints yêu cầu:
1. **JWT access token** hợp lệ — lấy từ \`POST /api/v1/auth/login\`
2. **Onboarding status = \`completed\`** — user phải hoàn thành onboarding trước

\`\`\`http
Authorization: Bearer <accessToken>
\`\`\`

| Trường hợp | HTTP | \`error_code\` |
|-----------|------|-------------|
| Thiếu hoặc invalid token | \`401\` | — (FastAPI default) |
| Token hợp lệ nhưng onboarding chưa xong | \`403\` | \`ONBOARDING_INCOMPLETE\` |

---

## 1. Submit Document

**\`POST /documents\`**

Ingest một document vào knowledge base. Server extract content, chunk, embed và index vào Qdrant. Client nhận \`document_id\` để dùng cho query sau.

> Yêu cầu \`Authorization: Bearer <accessToken>\` và onboarding completed.

### Request Body

| Field | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`source\` | \`string\` | ✅ | URL hoặc raw text content |
| \`source_type\` | \`string (enum)\` | ✅ | Loại nguồn — xem bảng bên dưới |
| \`domain_hint\` | \`string\` | ❌ | Gợi ý domain để phân loại (vd: \`"backend"\`, \`"ai"\`) |

#### \`source_type\` values

| Value | Mô tả |
|-------|-------|
| \`web\` | URL trang web |
| \`pdf\` | URL file PDF |
| \`text\` | Raw text content |
| \`git\` | URL Git repository |

\`\`\`json
{
  "source": "https://docs.python.org/3/library/asyncio.html",
  "source_type": "web",
  "domain_hint": "backend"
}
\`\`\`

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "document_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    "status": "COMPLETE"
  }
}
\`\`\`

| Field | Type | Mô tả |
|-------|------|-------|
| \`data.document_id\` | \`string\` | UUID của document đã index — dùng để filter trong research query |
| \`data.status\` | \`string\` | \`"COMPLETE"\` — đã index xong; \`"PROCESSING"\` — đang xử lý async (document > 25k words) |

> Nếu \`status = "PROCESSING"\`: document vẫn đang được index. Client nên đợi trước khi query để đảm bảo kết quả đầy đủ.

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| \`401\` | — | Missing hoặc invalid JWT |
| \`403\` | \`ONBOARDING_INCOMPLETE\` | User chưa hoàn thành onboarding |
| \`422\` | — | Request body sai format, thiếu field bắt buộc, \`source_type\` không hợp lệ |
| \`500\` | \`INGESTION_ERROR\` | Lỗi trong quá trình extract / embed / index |

\`\`\`json
{
  "status": "0",
  "error_code": "INGESTION_ERROR",
  "msg": "Failed to fetch URL: Connection timeout",
  "data": null
}
\`\`\`

---

## 2. Research Stream

**\`GET /research/stream\`**

Semantic search trên knowledge base + generate LLM answer. Trả về **Server-Sent Events (SSE)** stream. Client nhận events liên tục cho đến khi server đóng connection.

> Yêu cầu \`Authorization: Bearer <accessToken>\` và onboarding completed.

### Query Parameters

| Parameter | Type | Required | Default | Mô tả |
|-----------|------|----------|---------|-------|
| \`query\` | \`string\` | ✅ | — | Câu hỏi hoặc search query |
| \`role_id\` | \`string\` | ❌ | \`null\` | UUID của RoleKb — search trong collection riêng của role đó |
| \`document_id\` | \`string\` | ❌ | \`null\` | Giới hạn search trong 1 document cụ thể |
| \`top_k\` | \`integer\` | ❌ | \`10\` | Số chunks tối đa lấy về (min: \`1\`, max: \`100\`) |
| \`domain_filters\` | \`string[]\` | ❌ | \`[]\` | Lọc theo domain tags. Truyền nhiều lần để multi-filter |

\`\`\`http
GET /research/stream?query=How+does+asyncio+work&role_id=abc-123&top_k=5
Authorization: Bearer eyJhbGci...
\`\`\`

\`\`\`http
GET /research/stream?query=What+is+RAG&domain_filters=ai&domain_filters=backend
Authorization: Bearer eyJhbGci...
\`\`\`

### Response — SSE Stream

\`\`\`http
HTTP/1.1 200 OK
Content-Type: text/event-stream
Cache-Control: no-cache
X-Accel-Buffering: no
\`\`\`

Client nhận chuỗi events theo thứ tự sau:

\`\`\`
data: {"type": "PROGRESS", ...}

data: {"type": "RESULT", ...}
data: {"type": "RESULT", ...}

data: {"type": "ANSWER", ...}
\`\`\`

> Xem chi tiết từng event tại [SSE Event Reference](#sse-event-reference).

### Error Responses (trước khi stream bắt đầu)

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| \`401\` | — | Missing hoặc invalid JWT |
| \`403\` | \`ONBOARDING_INCOMPLETE\` | User chưa hoàn thành onboarding |
| \`422\` | — | Thiếu \`query\` parameter |

> **Lưu ý:** Lỗi xảy ra **bên trong stream** (sau khi HTTP 200 đã trả về) sẽ được emit dưới dạng \`ERROR\` event — không phải HTTP error. Client phải kiểm tra \`event.type === "ERROR"\`.

---

## SSE Event Reference

### PROGRESS

Luôn là event đầu tiên. Báo hiệu server đã bắt đầu xử lý.

\`\`\`json
{
  "type": "PROGRESS",
  "message": "Processing started",
  "document_id": ""
}
\`\`\`

### RESULT

Mỗi chunk tìm được với \`score >= 0.70\` sẽ emit một RESULT event. Có thể có nhiều RESULT hoặc không có.

\`\`\`json
{
  "type": "RESULT",
  "message": "<nội dung chunk>",
  "chunk_id": "chunk-uuid-string",
  "document_id": "doc-uuid-string",
  "score": 0.87,
  "domain_tags": ["backend", "python"],
  "chunk_index": 2
}
\`\`\`

| Field | Type | Mô tả |
|-------|------|-------|
| \`message\` | \`string\` | Nội dung text của chunk |
| \`chunk_id\` | \`string\` | ID của chunk trong Qdrant |
| \`document_id\` | \`string\` | UUID của document gốc |
| \`score\` | \`float\` | Relevance score (0.0 – 1.0). Chỉ trả về chunk có score ≥ 0.70 |
| \`domain_tags\` | \`string[]\` | Domain tags của chunk |
| \`chunk_index\` | \`integer\` | Vị trí chunk trong document gốc |

### ANSWER

LLM-generated answer dựa trên các RESULT chunks. Chỉ xuất hiện nếu LLM được cấu hình trên server.

\`\`\`json
{
  "type": "ANSWER",
  "message": "<câu trả lời đầy đủ từ LLM>",
  "document_id": ""
}
\`\`\`

> Nếu không có RESULT nào (không tìm được chunk liên quan), LLM vẫn trả lời từ general knowledge và index câu trả lời đó vào knowledge base để dùng cho query sau.

### ERROR

Lỗi xảy ra trong quá trình stream. Stream sẽ đóng sau event này.

\`\`\`json
{
  "type": "ERROR",
  "message": "Internal server error"
}
\`\`\`

---

## Error Code Catalog

| \`error_code\` | HTTP | Mô tả |
|-------------|------|-------|
| \`ONBOARDING_INCOMPLETE\` | \`403\` | User chưa hoàn thành onboarding — không thể dùng Documents / Research |
| \`INGESTION_ERROR\` | \`500\` | Lỗi trong quá trình extract / chunk / embed / index document |

---

## Full Flow Sequence

### Submit Document → Research

\`\`\`
Client                          Server                        Qdrant
  |                               |                               |
  |-- POST /documents ----------->|                               |
  |   Authorization: Bearer <at>  |                               |
  |   { source, source_type }     |-- extract content             |
  |                               |-- chunk + embed               |
  |                               |-- index chunks -------------->|
  |<-- 200 { document_id,         |                               |
  |          status: "COMPLETE" } |                               |
  |                               |                               |
  |-- GET /research/stream ------->|                               |
  |   ?query=...                  |-- emit PROGRESS               |
  |   Authorization: Bearer <at>  |-- search Qdrant ------------->|
  |                               |<-- top_k chunks --------------|
  |<-- data: PROGRESS             |-- filter score >= 0.70        |
  |<-- data: RESULT (chunk 1)     |-- emit RESULT events          |
  |<-- data: RESULT (chunk 2)     |                               |
  |                               |-- LLM chat(context + query)   |
  |<-- data: ANSWER               |                               |
  |   (stream closed)             |                               |
\`\`\`

### Research với role_id (RoleKb)

\`\`\`
Client                          Server                        Qdrant
  |                               |                               |
  |-- GET /research/stream ------->|                               |
  |   ?query=...&role_id=abc-123  |-- lookup role_kb_repo         |
  |   Authorization: Bearer <at>  |-- verify user_id ownership    |
  |                               |-- get qdrant_slug             |
  |                               |-- search collection           |
  |                               |   domain_role_kb_<uuid> ----->|
  |<-- data: PROGRESS             |<-- top_k chunks --------------|
  |<-- data: RESULT               |-- LLM với role system prompt  |
  |<-- data: ANSWER               |                               |
  |   (stream closed)             |                               |
\`\`\`

### Onboarding chưa xong → 403

\`\`\`
Client                          Server
  |                               |
  |-- POST /documents ----------->|
  |   Authorization: Bearer <at>  |-- decode JWT
  |   (onboarding: "pending")     |-- check onboarding_status
  |<-- 403 ONBOARDING_INCOMPLETE--|
\`\`\`
`;

export const onboardingDocContent = `# Onboarding API — Integration Docs

> **Base URL:** \`https://kbapi.pulsemarketspt.com\`
> **Content-Type:** \`application/json\` cho tất cả request (trừ \`POST /seed/file\` dùng \`multipart/form-data\`)
> **Auth:** \`Authorization: Bearer <accessToken>\` bắt buộc cho mọi endpoint
> **Version:** V1.0 — 2026-05-25

---

## Mục lục

- [Response Envelope](#response-envelope)
- [1. Get Onboarding State](#1-get-onboarding-state)
- [2. Get Role Options](#2-get-role-options)
- [3. Save Roles](#3-save-roles)
- [4. Seed Knowledge (URL / Text)](#4-seed-knowledge-url--text)
- [5. Seed Knowledge (File Upload)](#5-seed-knowledge-file-upload)
- [6. Get Seed Status](#6-get-seed-status)
- [7. Complete Onboarding](#7-complete-onboarding)
- [Error Code Catalog](#error-code-catalog)
- [Full Flow Sequence](#full-flow-sequence)

---

## Response Envelope

Mọi response đều wrap trong envelope sau:

\`\`\`json
// Success
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": { ... }
}

// Error
{
  "status": "0",
  "error_code": "ERROR_CODE",
  "msg": "Human-readable message",
  "data": { ... }
}
\`\`\`

---

## 1. Get Onboarding State

**\`GET /api/v1/onboarding/state\`**

Lấy trạng thái onboarding hiện tại của user: bước hiện tại, route tiếp theo, danh sách role đã chọn, và các source type được hỗ trợ.

### Headers

| Header | Required | Mô tả |
|--------|----------|-------|
| \`Authorization\` | ✅ | \`Bearer <accessToken>\` |

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "currentStep": "roles",
    "nextRoute": "/onboarding/roles",
    "roles": [
      {
        "id": "role-uuid-1",
        "roleName": "Backend Engineer",
        "roleGroup": "engineering",
        "roleOptionId": "opt-uuid-1",
        "isPrimary": true,
        "isCustom": false
      }
    ],
    "supportedSourceTypes": ["url", "text", "file_pdf", "file_txt", "file_md"]
  }
}
\`\`\`

| Field | Type | Mô tả |
|-------|------|-------|
| \`currentStep\` | string | Bước hiện tại: \`"roles"\`, \`"seed"\`, \`"complete"\` |
| \`nextRoute\` | string | Route FE nên redirect đến |
| \`roles\` | array | Danh sách role đã save (rỗng nếu chưa save) |
| \`supportedSourceTypes\` | array | Các loại nguồn có thể seed |

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 401 | \`UNAUTHORIZED\` | Access token không hợp lệ hoặc hết hạn |

---

## 2. Get Role Options

**\`GET /api/v1/onboarding/role-options\`**

Lấy danh sách role options có thể chọn, nhóm theo \`roleGroup\`.

### Headers

| Header | Required | Mô tả |
|--------|----------|-------|
| \`Authorization\` | ✅ | \`Bearer <accessToken>\` |

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "groups": [
      {
        "name": "engineering",
        "label": "Engineering",
        "options": [
          {
            "id": "opt-uuid-1",
            "roleName": "Backend Engineer",
            "description": "API design, database, server-side logic"
          },
          {
            "id": "opt-uuid-2",
            "roleName": "Frontend Engineer",
            "description": "UI development, browser APIs"
          }
        ]
      },
      {
        "name": "product",
        "label": "Product",
        "options": [ ... ]
      }
    ]
  }
}
\`\`\`

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 401 | \`UNAUTHORIZED\` | Access token không hợp lệ hoặc hết hạn |

---

## 3. Save Roles

**\`POST /api/v1/onboarding/roles\`**

Lưu danh sách role user đã chọn. Tạo \`RoleKb\` record cho mỗi role. Có thể gọi lại để cập nhật (idempotent).

### Headers

| Header | Required | Mô tả |
|--------|----------|-------|
| \`Authorization\` | ✅ | \`Bearer <accessToken>\` |

### Request Body

| Field | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`roles\` | array | ✅ | Danh sách role, ít nhất 1 phần tử |
| \`roles[].roleName\` | string | ✅ | Tên role |
| \`roles[].roleGroup\` | string | ✅ | Group của role (vd: \`"engineering"\`) |
| \`roles[].roleOptionId\` | string \\| null | ❌ | ID option từ \`/role-options\`. Null nếu \`isCustom: true\` |
| \`roles[].isPrimary\` | boolean | ✅ | \`true\` cho role chính (chỉ một role được là primary) |
| \`roles[].isCustom\` | boolean | ✅ | \`true\` nếu role do user tự nhập |

\`\`\`json
{
  "roles": [
    {
      "roleName": "Backend Engineer",
      "roleGroup": "engineering",
      "roleOptionId": "opt-uuid-1",
      "isPrimary": true,
      "isCustom": false
    },
    {
      "roleName": "DevOps",
      "roleGroup": "engineering",
      "roleOptionId": null,
      "isPrimary": false,
      "isCustom": true
    }
  ]
}
\`\`\`

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {}
}
\`\`\`

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 400 | \`ROLE_REQUIRED\` | Danh sách \`roles\` rỗng |
| 400 | \`INVALID_ROLE_SELECTION\` | Nhiều hơn 1 role có \`isPrimary: true\` |
| 400 | \`ROLE_OPTION_NOT_FOUND\` | \`roleOptionId\` không tồn tại trong hệ thống |
| 401 | \`UNAUTHORIZED\` | Access token không hợp lệ hoặc hết hạn |

---

## 4. Seed Knowledge (URL / Text)

**\`POST /api/v1/onboarding/seed\`**

Gửi yêu cầu seed knowledge từ URL hoặc plain text. Job chạy bất đồng bộ — nhận \`jobId\` để optionally poll status.

### Headers

| Header | Required | Mô tả |
|--------|----------|-------|
| \`Authorization\` | ✅ | \`Bearer <accessToken>\` |

### Request Body

| Field | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`roleKbId\` | string (uuid) | ✅ | ID của RoleKb muốn seed vào |
| \`sourceType\` | \`"url"\` \\| \`"text"\` | ✅ | Loại nguồn |
| \`content\` | string | ✅ | URL (khi \`sourceType: "url"\`) hoặc plain text (khi \`sourceType: "text"\`) |

> \`sourceType\` chỉ nhận đúng \`"url"\` hoặc \`"text"\`. Giá trị khác → \`422 VALIDATION_ERROR\`.

\`\`\`json
{
  "roleKbId": "kb-uuid-1",
  "sourceType": "url",
  "content": "https://docs.python.org/3/library/asyncio.html"
}
\`\`\`

\`\`\`json
{
  "roleKbId": "kb-uuid-1",
  "sourceType": "text",
  "content": "FastAPI uses Starlette under the hood and Pydantic for data validation..."
}
\`\`\`

### Response \`202\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "jobId": "job-uuid-1"
  }
}
\`\`\`

> HTTP \`202 Accepted\` — job chạy nền, FE không cần đợi. Gọi \`POST /complete\` ngay sau khi nhận \`202\`. \`jobId\` dùng để poll status nếu muốn hiển thị progress (optional).

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 400 | \`UNSUPPORTED_SOURCE_TYPE\` | \`sourceType\` không phải \`"url"\` hoặc \`"text"\` |
| 400 | \`SSRF_BLOCKED\` | URL trỏ vào private IP, localhost, hoặc bị chặn |
| 400 | \`KNOWLEDGE_SOURCE_NOT_FOUND\` | \`roleKbId\` không tồn tại hoặc không thuộc user |
| 401 | \`UNAUTHORIZED\` | Access token không hợp lệ hoặc hết hạn |
| 403 | \`ROLE_NOT_OWNED\` | \`roleKbId\` thuộc user khác |
| 422 | \`VALIDATION_ERROR\` | Body sai format hoặc \`sourceType\` không hợp lệ |

---

## 5. Seed Knowledge (File Upload)

**\`POST /api/v1/onboarding/seed/file\`**

Upload file để seed knowledge. Hỗ trợ PDF, TXT, Markdown. Job chạy bất đồng bộ.

> **Content-Type:** \`multipart/form-data\`

### Headers

| Header | Required | Mô tả |
|--------|----------|-------|
| \`Authorization\` | ✅ | \`Bearer <accessToken>\` |
| \`Content-Type\` | ✅ | \`multipart/form-data\` |

### Form Fields

| Field | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`roleKbId\` | string (uuid) | ✅ | ID của RoleKb muốn seed vào |
| \`sourceType\` | \`"file_pdf"\` \\| \`"file_txt"\` \\| \`"file_md"\` | ✅ | Loại file |
| \`file\` | binary | ✅ | File cần upload |

\`\`\`bash
curl -X POST https://kbapi.pulsemarketspt.com/api/v1/onboarding/seed/file \\
  -H "Authorization: Bearer <accessToken>" \\
  -F "roleKbId=kb-uuid-1" \\
  -F "sourceType=file_pdf" \\
  -F "file=@/path/to/document.pdf"
\`\`\`

### Response \`202\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "jobId": "job-uuid-2"
  }
}
\`\`\`

> HTTP \`202 Accepted\`. Job chạy nền — gọi \`POST /complete\` ngay. \`jobId\` dùng để poll status nếu muốn hiển thị progress (optional).

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 400 | \`UNSUPPORTED_SOURCE_TYPE\` | \`sourceType\` không phải \`file_pdf\`, \`file_txt\`, hoặc \`file_md\` |
| 400 | \`FILE_NOT_FOUND\` | File không tồn tại sau khi upload |
| 400 | \`KNOWLEDGE_SOURCE_NOT_FOUND\` | \`roleKbId\` không tồn tại hoặc không thuộc user |
| 401 | \`UNAUTHORIZED\` | Access token không hợp lệ hoặc hết hạn |
| 403 | \`ROLE_NOT_OWNED\` | \`roleKbId\` thuộc user khác |

---

## 6. Get Seed Status

**\`GET /api/v1/onboarding/seed/status/{jobId}\`**

Poll trạng thái của một seed job. **Optional** — dùng khi FE muốn hiển thị progress hoặc thông báo lỗi cụ thể. Chỉ owner của job mới xem được.

### Headers

| Header | Required | Mô tả |
|--------|----------|-------|
| \`Authorization\` | ✅ | \`Bearer <accessToken>\` |

### Path Params

| Param | Type | Required | Mô tả |
|-------|------|----------|-------|
| \`jobId\` | string | ✅ | Job ID nhận từ \`/seed\` hoặc \`/seed/file\` |

### Response \`200\` — Job đang xử lý

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "status": "processing",
    "progress": 40,
    "source_id": "source-uuid-1",
    "updated_at": "2026-05-25T10:30:00+00:00",
    "error": null
  }
}
\`\`\`

### Response \`200\` — Job hoàn thành

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "status": "done",
    "progress": 100,
    "source_id": "source-uuid-1",
    "updated_at": "2026-05-25T10:30:45+00:00",
    "error": null
  }
}
\`\`\`

### Response \`200\` — Job thất bại (vd: PDF toàn ảnh)

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "status": "failed",
    "progress": 0,
    "source_id": "source-uuid-1",
    "updated_at": "2026-05-25T10:30:12+00:00",
    "error": "Document contains no extractable text — may be a scanned image PDF."
  }
}
\`\`\`

### Response \`200\` — Job không tồn tại

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "status": "not_found",
    "progress": 0,
    "source_id": null,
    "updated_at": null
  }
}
\`\`\`

> Khi \`status: "not_found"\`, server trả \`200\` (không phải \`404\`). Job có thể chưa khởi tạo trong Redis — retry sau 1–2 giây.

### \`status\` values

| Value | Mô tả |
|-------|-------|
| \`"queued"\` | Job đã được enqueue, chưa xử lý |
| \`"processing"\` | Đang xử lý (extract → route → index) |
| \`"done"\` | Hoàn thành, knowledge đã được index |
| \`"failed"\` | Thất bại — xem field \`error\` để biết lý do |
| \`"not_found"\` | Job ID không tìm thấy trong Redis |

### \`progress\` values

| Value | Stage |
|-------|-------|
| \`10\` | Bắt đầu xử lý |
| \`40\` | Extract xong, đang route |
| \`70\` | Route xong, đang index |
| \`100\` | Hoàn thành |
| \`0\` | Thất bại |

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 401 | \`UNAUTHORIZED\` | Access token không hợp lệ hoặc hết hạn |
| 404 | \`KNOWLEDGE_SOURCE_NOT_FOUND\` | Job tồn tại trong Redis nhưng source thuộc user khác |

---

## 7. Complete Onboarding

**\`POST /api/v1/onboarding/complete\`**

Đánh dấu onboarding hoàn thành. Cập nhật \`onboarding_status → "completed"\` trong DB.

> FE gọi endpoint này **ngay sau khi** nhận \`202\` từ \`/seed\` hoặc \`/seed/file\` — không cần đợi seed job xong. Knowledge được index ngầm trong nền. Sau khi gọi \`/complete\`, refresh token để JWT claim \`onboardingStatus\` cập nhật thành \`"completed"\`.

### Headers

| Header | Required | Mô tả |
|--------|----------|-------|
| \`Authorization\` | ✅ | \`Bearer <accessToken>\` |

### Response \`200\`

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "nextRoute": "/dashboard"
  }
}
\`\`\`

### Error Responses

| HTTP | \`error_code\` | Khi nào |
|------|-------------|---------|
| 401 | \`UNAUTHORIZED\` | Access token không hợp lệ hoặc hết hạn |
| 409 | \`ONBOARDING_ALREADY_COMPLETED\` | User đã complete onboarding trước đó |

---

## Error Code Catalog

| \`error_code\` | HTTP | Mô tả |
|-------------|------|-------|
| \`VALIDATION_ERROR\` | 422 | Request body sai format, thiếu field bắt buộc, hoặc \`sourceType\` không hợp lệ |
| \`UNAUTHORIZED\` | 401 | Access token không hợp lệ, hết hạn, hoặc bị blacklist |
| \`ROLE_REQUIRED\` | 400 | Danh sách \`roles\` rỗng khi save |
| \`ROLE_NOT_OWNED\` | 403 | \`roleKbId\` không thuộc user hiện tại |
| \`ROLE_OPTION_NOT_FOUND\` | 400 | \`roleOptionId\` không tồn tại |
| \`INVALID_ROLE_SELECTION\` | 400 | Nhiều role có \`isPrimary: true\` |
| \`UNSUPPORTED_SOURCE_TYPE\` | 400 | \`sourceType\` không được hỗ trợ |
| \`SSRF_BLOCKED\` | 400 | URL trỏ vào private/internal network |
| \`KNOWLEDGE_SOURCE_NOT_FOUND\` | 400/404 | \`roleKbId\` hoặc source không tồn tại, hoặc job thuộc user khác |
| \`FILE_NOT_FOUND\` | 400 | File không tìm thấy sau upload |
| \`ONBOARDING_ALREADY_COMPLETED\` | 409 | Gọi \`/complete\` khi đã completed |
| \`EMPTY_DOCUMENT\` | — | PDF toàn ảnh — xuất hiện trong \`data.error\` của seed status khi \`status: "failed"\` |

> \`EMPTY_DOCUMENT\` không trả như HTTP error. Nó nằm trong \`data.error\` của \`GET /seed/status\` khi \`status: "failed"\`.

---

## Full Flow Sequence

### Happy Path: Login → Onboarding → Dashboard

\`\`\`
Client                          Server
  |                               |
  |-- POST /auth/login ----------->|
  |<-- 200 { accessToken,          |
  |          onboardingStatus:     |
  |          "pending" } ----------|
  |                               |
  |-- GET /onboarding/state ------>|
  |<-- 200 { currentStep: "roles", |
  |          nextRoute: "/roles" } |
  |                               |
  |-- GET /onboarding/role-options>|
  |<-- 200 { groups: [...] } ------|
  |                               |
  |-- POST /onboarding/roles ------>|
  |<-- 200 {} --------------------|
  |                               |
  |-- POST /onboarding/seed/file -->|
  |   (multipart, file_pdf)        |-- save tmp → enqueue job (nền)
  |<-- 202 { jobId: "job-1" } -----|
  |                               |
  |-- POST /onboarding/complete -->| ← gọi ngay, không cần đợi job
  |                               |-- UPDATE onboarding_status
  |<-- 200 { nextRoute:            |
  |          "/dashboard" } -------|
  |                               |
  |-- POST /auth/refresh ---------->|
  |<-- 200 { accessToken }         |
  |   (JWT: onboardingStatus =     |
  |    "completed") --------------|
\`\`\`

> Seed job tiếp tục chạy nền sau khi FE đã redirect về \`/dashboard\`. Knowledge sẽ sẵn sàng khi job hoàn thành.

### PDF Toàn Ảnh — Dùng GET /seed/status để thông báo lỗi (Optional)

\`\`\`
Client                          Server                        Redis
  |                               |                               |
  |-- POST /onboarding/seed/file -->|                               |
  |   (image-only PDF)             |-- enqueue job ---------------->|
  |<-- 202 { jobId: "job-2" } -----|                               |
  |                               |                               |
  |   (FE muốn hiển thị lỗi cụ thể)|                               |
  |-- GET /seed/status/job-2 ----->|                               |
  |                               |-- extract → word_count=0       |
  |                               |-- failed, error set ---------->|
  |<-- 200 {                       |                               |
  |   status: "failed",            |                               |
  |   error: "Document contains    |                               |
  |   no extractable text —        |                               |
  |   may be a scanned image PDF." |                               |
  | } -----------------------------|                               |
\`\`\`

> FE hiển thị \`data.error\` cho user khi \`status: "failed"\`. User có thể upload lại file khác.

### Token Hết Hạn Giữa Chừng

\`\`\`
Client                          Server
  |                               |
  |-- POST /onboarding/complete -->|
  |   Authorization: Bearer <at>  |-- decode JWT → expired
  |<-- 401 { UNAUTHORIZED } ------|
  |                               |
  |-- POST /auth/refresh ---------->|
  |<-- 200 { accessToken,          |
  |          refreshToken } -------|
  |                               |
  |-- POST /onboarding/complete -->| (retry với token mới)
  |<-- 200 { nextRoute: "/dashboard"}
\`\`\`
`;

export const usersDocContent = `# Users API — Integration Docs

> **Base URL:** \`https://kbapi.pulsemarketspt.com\`
> **Content-Type:** \`application/json\`
> **Auth:** \`Authorization: Bearer <accessToken>\` bắt buộc
> **Version:** V1.0 — 2026-06-09

---

## Mục lục

- [Response Envelope](#response-envelope)
- [1. Get Current User](#1-get-current-user)
- [Error Code Catalog](#error-code-catalog)

---

## Response Envelope

Mọi response đều wrap trong envelope sau:

\`\`\`json
// Success
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": { ... }
}

// Error
{
  "status": "0",
  "error_code": "ERROR_CODE",
  "msg": "Human-readable message",
  "data": {}
}
\`\`\`

---

## 1. Get Current User

**\`GET /api/v1/users/me\`**

Lấy thông tin của user đang đăng nhập kèm danh sách role KB. Dùng để:
- Hiển thị profile (tên, email, plan)
- Lấy \`roles[].id\` để truyền vào \`role_id\` khi gọi \`/research/stream\`
- Lấy \`roles[].id\` để truyền vào \`roleKbId\` khi gọi \`/onboarding/seed\`

### Headers

| Header | Required | Mô tả |
|--------|----------|-------|
| \`Authorization\` | ✅ | \`Bearer <accessToken>\` |

### Request

Không có request body hay query params.

### Response Body (\`data\`)

| Field | Type | Mô tả |
|-------|------|-------|
| \`id\` | \`string\` (UUID) | User ID |
| \`email\` | \`string\` | Email đăng nhập |
| \`firstName\` | \`string\` | Tên |
| \`lastName\` | \`string\` | Họ |
| \`plan\` | \`string\` | \`"free"\` hoặc \`"pro"\` |
| \`onboardingStatus\` | \`string\` | \`"pending"\` hoặc \`"completed"\` |
| \`roles\` | \`array\` | Danh sách role KB (rỗng nếu chưa setup) |
| \`roles[].id\` | \`string\` (UUID) | **Role KB ID** — dùng cho research/seed |
| \`roles[].roleName\` | \`string\` | Tên role (VD: \`"Backend Engineer"\`) |
| \`roles[].roleGroup\` | \`string\` | Nhóm: \`"engineering"\`, \`"business"\`, \`"design"\`, \`"data"\`, \`"other"\` |
| \`roles[].isPrimary\` | \`boolean\` | Role chính của user |
| \`roles[].isCustom\` | \`boolean\` | Role do user tự nhập (không từ template) |

### Sample Response — Success

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "id": "a3f2c1d0-1234-5678-abcd-ef0123456789",
    "email": "nguyen.van.a@example.com",
    "firstName": "An",
    "lastName": "Nguyễn",
    "plan": "free",
    "onboardingStatus": "completed",
    "roles": [
      {
        "id": "51b81891-1124-4083-b9f2-ee5b544c6293",
        "roleName": "Backend Engineer",
        "roleGroup": "engineering",
        "isPrimary": true,
        "isCustom": false
      },
      {
        "id": "7d9e2f3a-aaaa-bbbb-cccc-000011112222",
        "roleName": "Data Analyst",
        "roleGroup": "data",
        "isPrimary": false,
        "isCustom": false
      }
    ]
  }
}
\`\`\`

### Sample Response — Chưa có role

\`\`\`json
{
  "status": "1",
  "error_code": "0",
  "msg": "Success",
  "data": {
    "id": "a3f2c1d0-1234-5678-abcd-ef0123456789",
    "email": "nguyen.van.a@example.com",
    "firstName": "An",
    "lastName": "Nguyễn",
    "plan": "free",
    "onboardingStatus": "pending",
    "roles": []
  }
}
\`\`\`

### Error Responses

| HTTP | \`error_code\` | Nguyên nhân |
|------|-------------|-------------|
| \`401\` | \`UNAUTHORIZED\` | Token thiếu, hết hạn, hoặc không hợp lệ |
| \`404\` | \`USER_NOT_FOUND\` | User không tồn tại trong DB (hiếm gặp) |
| \`503\` | \`SERVICE_UNAVAILABLE\` | Server chưa kết nối DB |

---

## Error Code Catalog

| \`error_code\` | HTTP | Mô tả |
|-------------|------|-------|
| \`UNAUTHORIZED\` | 401 | Không có hoặc token không hợp lệ |
| \`USER_NOT_FOUND\` | 404 | User không tồn tại |
| \`SERVICE_UNAVAILABLE\` | 503 | DB chưa được cấu hình |

---

## Curl Example

\`\`\`bash
curl -X GET "https://kbapi.pulsemarketspt.com/api/v1/users/me" \\
  -H "Authorization: Bearer <accessToken>"
\`\`\`

### Sau khi có \`roles[].id\`, dùng ngay để research:

\`\`\`bash
# Lấy role_kb_id từ response ở trên, ví dụ: 51b81891-1124-4083-b9f2-ee5b544c6293
curl -N -X GET "https://kbapi.pulsemarketspt.com/research/stream\\
?query=giải thích về microservices\\
&role_id=51b81891-1124-4083-b9f2-ee5b544c6293" \\
  -H "Authorization: Bearer <accessToken>" \\
  -H "Accept: text/event-stream"
\`\`\`
`;

export const apiDocsList: ApiDocItem[] = [
  { id: 'auth', title: 'Authentication API', filename: 'API_Auth_Docs.md', content: authDocContent },
  { id: 'documents', title: 'Documents & Research API', filename: 'API_Documents_Research_Docs.md', content: documentsDocContent },
  { id: 'onboarding', title: 'Onboarding API', filename: 'API_Onboarding_Docs.md', content: onboardingDocContent },
  { id: 'users', title: 'Users API', filename: 'API_Users_Docs.md', content: usersDocContent }
];
